// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4CitT6ooctWH3hxlmgfC3VMrhtDPzaNo',
    appId: '1:875475671258:web:7618ddbed3233702efade3',
    messagingSenderId: '875475671258',
    projectId: 'maxmagri-c5ded',
    authDomain: 'maxmagri-c5ded.firebaseapp.com',
    storageBucket: 'maxmagri-c5ded.appspot.com',
    measurementId: 'G-GEJNDSXP82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJhljPmimPdZRzcJQsRhhN3j-F1Cska3o',
    appId: '1:875475671258:android:3ec773b53401169defade3',
    messagingSenderId: '875475671258',
    projectId: 'maxmagri-c5ded',
    storageBucket: 'maxmagri-c5ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKmHOGJE4LiXWgv5JWqm9-NrBPJS57hk8',
    appId: '1:875475671258:ios:c3f5726683c99bb1efade3',
    messagingSenderId: '875475671258',
    projectId: 'maxmagri-c5ded',
    storageBucket: 'maxmagri-c5ded.appspot.com',
    iosClientId: '875475671258-p3dsbmk3iflvoke10m6iuh2dsrm1bolt.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxmagri',
  );
}
